### ISSUE TITLE
Court rating

### ISSUE THREAD

**Issue by chrisdesilva** [chrisdesilva/pickup#30]
Add a court rating feature to the court modals. Users should be signed in to leave ratings but anyone should be able to see the ratings publicly.

**Comment by mlimos** [comment]
@chrisdesilva hi, can i take this one if nobody else has claimed it?

**Comment by chrisdesilva** [comment]
Definitely! Thanks for helping out

**Comment by mlimos** [comment]
@chrisdesilva beginning to work on this now and had a quick question. do you want users to be able to add a rating both when the court is added and have an option to rate whenever a user is signed in? if you also want the latter option, then how would you like to handle multiple court ratings by different users? you could potentially average them across the board, but I did want to hear your thoughts on it.

**Comment by chrisdesilva** [comment]
Great question! I like the idea of an average rating with the total number of submissions displayed. So a court could have an average of 4.2 stars (or whatever symbol you want) based on 15 reviews, for example.

**Comment by mlimos** [comment]
Ok, great! I'll look to implement something along those lines.
