### ISSUE TITLE
no mention of env variables setup

### ISSUE THREAD

**Issue by cdrani** [chrisdesilva/pickup#7]
This project requires both a dark sky and google maps api keys, but there's no mention of this anywhere. Projects like these will usually include a sample file with the keys. For ex:
// sample.env
```
REACT_DARK_SKY_API_KEY=keyfordarksky
REACT_GOOGLE_MAPS_KEY=keyforgooglemaps
```
Then there would be instructions in the readme telling people: 
`cp sample.env .env` and add in their own keys with possibly links to the sites to set this up.

**Comment by chrisdesilva** [comment]
Thanks for posting this issue, Charles! I'm working on getting a fix for this after reviewing best practices.

**Comment by chrisdesilva** [comment]
@cdrani Just updated the readme and added a .env.sample per your feedback. Any further recommendations to make it easier for folks to contribute?

**Comment by chrisdesilva** [comment]
Marking this issue as closed but will welcome further updates to make things more clear for contributors.
